"""add fleet_owners, users, vehicle.fleet_owner_id

Revision ID: 5e61bb2d64d1
Revises: 75a01f7b9736
Create Date: 2026-09-02 10:19:32.435339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e61bb2d64d1'
down_revision: Union[str, Sequence[str], None] = '75a01f7b9736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('fleet_owner_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("role in ('admin','fleet_owner')", name='ck_user_role_valid'),
    sa.ForeignKeyConstraint(['fleet_owner_id'], ['fleet_owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('vehicles', sa.Column('fleet_owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicles_fleet_owner_id'), 'vehicles', ['fleet_owner_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'fleet_owners', ['fleet_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_fleet_owner_id'), table_name='vehicles')
    op.drop_column('vehicles', 'fleet_owner_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fleet_owners')
    # ### end Alembic commands ###
