"""add raw_score to rule_config

Revision ID: 75a01f7b9736
Revises: a5982a8af598
Create Date: 2026-08-19 12:53:00.488476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a01f7b9736'
down_revision: Union[str, Sequence[str], None] = 'a5982a8af598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default handles any pre-existing rows (e.g. rules built before
    # this column existed); new inserts always supply an explicit value.
    op.add_column(
        'rule_config',
        sa.Column('raw_score', sa.Float(), nullable=False, server_default='0.0'),
    )
    op.alter_column('rule_config', 'raw_score', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_config', 'raw_score')
    # ### end Alembic commands ###
