"""initial schema: vehicles, parts, failures, telematics, rule_config, predictions

Revision ID: a5982a8af598
Revises: 
Create Date: 2026-08-18 06:52:29.965806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5982a8af598'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('part_code', sa.String(length=20), nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('design_life_km', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('part_code')
    )
    op.create_table('vehicles',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('total_km_driven', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('vin')
    )
    op.create_table('failures',
    sa.Column('job_card_id', sa.String(length=30), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('part_code', sa.String(length=20), nullable=False),
    sa.Column('failure_date', sa.Date(), nullable=False),
    sa.Column('odometer_at_failure_km', sa.Integer(), nullable=False),
    sa.Column('replaced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['part_code'], ['parts.part_code'], ),
    sa.ForeignKeyConstraint(['vin'], ['vehicles.vin'], ),
    sa.PrimaryKeyConstraint('job_card_id')
    )
    op.create_index(op.f('ix_failures_part_code'), 'failures', ['part_code'], unique=False)
    op.create_index(op.f('ix_failures_vin'), 'failures', ['vin'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('part_code', sa.String(length=20), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=False),
    sa.Column('estimated_window_days', sa.Integer(), nullable=True),
    sa.Column('rul_km', sa.Integer(), nullable=True),
    sa.Column('rul_days', sa.Integer(), nullable=True),
    sa.Column('top_signals', sa.String(length=255), nullable=True),
    sa.Column('computed_date', sa.Date(), nullable=False),
    sa.CheckConstraint("risk_tier in ('Green','Amber','Red')", name='ck_risk_tier_valid'),
    sa.ForeignKeyConstraint(['part_code'], ['parts.part_code'], ),
    sa.ForeignKeyConstraint(['vin'], ['vehicles.vin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin', 'part_code', 'computed_date', name='uq_prediction_vin_part_date')
    )
    op.create_index(op.f('ix_predictions_part_code'), 'predictions', ['part_code'], unique=False)
    op.create_index(op.f('ix_predictions_vin'), 'predictions', ['vin'], unique=False)
    op.create_table('rule_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_code', sa.String(length=20), nullable=False),
    sa.Column('signal', sa.String(length=50), nullable=False),
    sa.Column('correlation_weight', sa.Float(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['part_code'], ['parts.part_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_code', 'signal', 'method', name='uq_rule_part_signal_method')
    )
    op.create_index(op.f('ix_rule_config_part_code'), 'rule_config', ['part_code'], unique=False)
    op.create_table('telematics_weekly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('coolant_temp_variance', sa.Float(), nullable=False),
    sa.Column('oil_pressure_dips', sa.Integer(), nullable=False),
    sa.Column('battery_voltage_sag', sa.Float(), nullable=False),
    sa.Column('dtc_recurrence_rate', sa.Float(), nullable=False),
    sa.Column('harsh_braking_frequency', sa.Float(), nullable=False),
    sa.Column('overload_duty_share', sa.Float(), nullable=False),
    sa.Column('high_rpm_dwell_time', sa.Float(), nullable=False),
    sa.Column('short_trip_ratio', sa.Float(), nullable=False),
    sa.Column('idle_time_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vin'], ['vehicles.vin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin', 'week_start_date', name='uq_telematics_vin_week')
    )
    op.create_index(op.f('ix_telematics_weekly_vin'), 'telematics_weekly', ['vin'], unique=False)
    op.create_index(op.f('ix_telematics_weekly_week_start_date'), 'telematics_weekly', ['week_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telematics_weekly_week_start_date'), table_name='telematics_weekly')
    op.drop_index(op.f('ix_telematics_weekly_vin'), table_name='telematics_weekly')
    op.drop_table('telematics_weekly')
    op.drop_index(op.f('ix_rule_config_part_code'), table_name='rule_config')
    op.drop_table('rule_config')
    op.drop_index(op.f('ix_predictions_vin'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_part_code'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_failures_vin'), table_name='failures')
    op.drop_index(op.f('ix_failures_part_code'), table_name='failures')
    op.drop_table('failures')
    op.drop_table('vehicles')
    op.drop_table('parts')
    # ### end Alembic commands ###
